//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace WuKeSong.Models
{
    public partial class CDREntities : DbContext
    {
        public CDREntities()
            : base("name=CDREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<EXAM_DATA> EXAM_DATA { get; set; }
        public DbSet<EXAM_ITEM> EXAM_ITEM { get; set; }
        public DbSet<EXAM_MASTER> EXAM_MASTER { get; set; }
        public DbSet<EXAM_REPORT> EXAM_REPORT { get; set; }
        public DbSet<LAB_TEST_DATA> LAB_TEST_DATA { get; set; }
        public DbSet<LAB_TEST_MASTER> LAB_TEST_MASTER { get; set; }
        public DbSet<MASTER_PATIENT_INDEX> MASTER_PATIENT_INDEX { get; set; }
        public DbSet<PATIENT_VISIT> PATIENT_VISIT { get; set; }
    }
}
