//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WuKeSong.Models
{
    public partial class EXAM_ITEM
    {
        public decimal SERIAL_NO { get; set; }
        public string EXAM_REQ_ID { get; set; }
        public string EXAM_ID { get; set; }
        public Nullable<int> EXAM_ITEM_NO { get; set; }
        public string EXAM_CLASS { get; set; }
        public string EXAM_SUB_CLASS { get; set; }
        public string EXAM_ITEM_NAME { get; set; }
        public string EXAM_ITEM_CODE { get; set; }
    }
    
}
