//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WuKeSong.Models
{
    public partial class LAB_TEST_DATA
    {
        public string TEST_DATA_ID { get; set; }
        public string PATIENT_ID { get; set; }
        public string VISIT_ID { get; set; }
        public string TEST_ID { get; set; }
        public string TEST_ITEM_NO { get; set; }
        public string TEST_ITEM_NAME { get; set; }
        public string TEST_ITEM_CODE { get; set; }
        public string RESULT { get; set; }
        public string UNITS { get; set; }
        public string ABNORMAL_INDICATOR { get; set; }
        public string NORMAL_REFERENCE_VALUES { get; set; }
        public string INSTRUMENT_ID { get; set; }
        public Nullable<System.DateTime> RESULT_DATE_TIME { get; set; }
    }
    
}
