//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WuKeSong.Models
{
    public partial class MASTER_PATIENT_INDEX
    {
        public decimal SERIAL_NO { get; set; }
        public string PATIENT_ID { get; set; }
        public string NAME { get; set; }
        public string NAME_PHONETIC { get; set; }
        public string GENDER { get; set; }
        public System.DateTime DATE_OF_BIRTH { get; set; }
        public string BIRTH_PLACE { get; set; }
        public string NATIONALITY { get; set; }
        public string ETHNIC_GROUP { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string CAREER { get; set; }
        public string DEGREE { get; set; }
        public string BLOOD_TYPE_ABO { get; set; }
        public string BLOOD_TYPE_RH { get; set; }
        public string IDENTITY_CARD_NO { get; set; }
        public string HOUSEHOLD_NO { get; set; }
        public string PASSPORT_NO { get; set; }
        public string MILITARY_ID { get; set; }
        public string HEALTH_INSURANCE_ID { get; set; }
        public string HEALTH_CARD_NO { get; set; }
        public string EMAIL { get; set; }
        public string MAILING_ADDRESS { get; set; }
        public string ZIP_CODE { get; set; }
        public string PHONE_NO_MOBILE { get; set; }
        public string PHONE_NO_HOME { get; set; }
        public string PHONE_NO_BUSINESS { get; set; }
        public string DEATH_INDICATOR { get; set; }
        public Nullable<System.DateTime> DEATH_TIME { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_MODIFY_DATE { get; set; }
        public string LAST_MODIFIED_BY { get; set; }
        public string VOIDED_INDICATOR { get; set; }
        public Nullable<System.DateTime> VOIDED_DATE { get; set; }
        public string VOIDED_BY { get; set; }
        public string REF_PATIENT_ID { get; set; }
        public string INPATIENTNO { get; set; }
        public string OUTPATIENTNO { get; set; }
        public string EMERGENCYNO { get; set; }
    }
    
}
