//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SanQingShan.Models
{
    public partial class Concept
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string CodingSystem { get; set; }
        public string Description { get; set; }
        public string Literal { get; set; }
    }
    
}
