//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SanQingShan.Models
{
    public partial class CP_VISIT
    {
        public int Id { get; set; }
        public string HOSPITAL_ID { get; set; }
        public string OUTPATIENT_ID { get; set; }
        public string INPATIENT_NO { get; set; }
        public string CP_ID { get; set; }
        public string VISIT_NO { get; set; }
        public Nullable<System.DateTime> ADMISSION_TIME { get; set; }
        public Nullable<System.DateTime> DISCHARGE_TIME { get; set; }
        public string DISCHARGE_TYPE { get; set; }
        public string DIAGNOSIS { get; set; }
        public string STRUCTURED_DIAGNOSIS { get; set; }
        public Nullable<System.DateTime> DIAGNOSIS_TIME { get; set; }
        public Nullable<System.DateTime> BIRTHDAY { get; set; }
        public string GENDER { get; set; }
        public string OCCUPATION { get; set; }
        public string CONDITION { get; set; }
        public string DEPARTMENT { get; set; }
        public string TOTAL_COSTS { get; set; }
        public string TOTAL_PAYMENTS { get; set; }
        public string DOCTOR { get; set; }
    }
    
}
