//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace WuKeSong.Models
{
    public partial class DictContainer : DbContext
    {
        public DictContainer()
            : base("name=DictContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACTION_ADT_DICT> ACTION_ADT_DICT { get; set; }
        public DbSet<ADMIN_ORDERS_DICT> ADMIN_ORDERS_DICT { get; set; }
        public DbSet<ADMISSION_CAUSE_DICT> ADMISSION_CAUSE_DICT { get; set; }
        public DbSet<ANAESTHESIA_DICT> ANAESTHESIA_DICT { get; set; }
        public DbSet<AREA_DICT> AREA_DICT { get; set; }
        public DbSet<CHARGE_TYPE_DICT> CHARGE_TYPE_DICT { get; set; }
        public DbSet<CLINIC_CLASS_DICT> CLINIC_CLASS_DICT { get; set; }
        public DbSet<CLINIC_ITEM_DICT> CLINIC_ITEM_DICT { get; set; }
        public DbSet<COUNTRY_DICT> COUNTRY_DICT { get; set; }
        public DbSet<DIAGNOSIS_DICT> DIAGNOSIS_DICT { get; set; }
        public DbSet<DIAGNOSIS_TYPE_DICT> DIAGNOSIS_TYPE_DICT { get; set; }
        public DbSet<DOC_TYPE_DICT> DOC_TYPE_DICT { get; set; }
        public DbSet<DRUG_CLASS_DICT> DRUG_CLASS_DICT { get; set; }
        public DbSet<EXAM_CLASS_DICT> EXAM_CLASS_DICT { get; set; }
        public DbSet<EXAM_MODE_DICT> EXAM_MODE_DICT { get; set; }
        public DbSet<EXAM_SUBCLASS_DICT> EXAM_SUBCLASS_DICT { get; set; }
        public DbSet<INSURANCE_TYPE_DICT> INSURANCE_TYPE_DICT { get; set; }
        public DbSet<LAB_TEST_RESULT_DICT> LAB_TEST_RESULT_DICT { get; set; }
        public DbSet<NATION_DICT> NATION_DICT { get; set; }
        public DbSet<OPERATION_DICT> OPERATION_DICT { get; set; }
        public DbSet<PATIENT_CLASS_DICT> PATIENT_CLASS_DICT { get; set; }
        public DbSet<SEGMENT_TYPE_DICT> SEGMENT_TYPE_DICT { get; set; }
        public DbSet<TITLE_DICT> TITLE_DICT { get; set; }
        public DbSet<TOP_UNIT_DICT> TOP_UNIT_DICT { get; set; }
        public DbSet<UNITS_IN_CONTRACT_DICT> UNITS_IN_CONTRACT_DICT { get; set; }
        public DbSet<VISIT_CLASS_DICT> VISIT_CLASS_DICT { get; set; }
        public DbSet<VITAL_SIGNS_DICT> VITAL_SIGNS_DICT { get; set; }
        public DbSet<WOUND_GRADE_DICT> WOUND_GRADE_DICT { get; set; }
    }
}
