//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WuKeSong.Models
{
    public partial class EXAM_MASTER
    {
        public string EXAM_ID { get; set; }
        public string PATIENT_ID { get; set; }
        public string VISIT_ID { get; set; }
        public string EXAM_REQ_ID { get; set; }
        public string HIS_EXAM_ID { get; set; }
        public string EXAM_DEPT_NAME { get; set; }
        public string EXAM_DEPT_CODE { get; set; }
        public Nullable<System.DateTime> SCHEDULED_DATE_TIME { get; set; }
    }
    
}
