//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WuKeSong.Models
{
    public partial class EXAM_DATA
    {
        public string EXAM_ID { get; set; }
        public int DATA_NO { get; set; }
        public string DATA_TYPE { get; set; }
        public string SERIES_NO { get; set; }
        public string IMAGE_NO { get; set; }
        public Nullable<int> IMAGE_FLAG { get; set; }
        public string FIRST_MEDIA_NAME { get; set; }
        public string FIRST_PATH { get; set; }
        public string SECOND_MEDIA_NAME { get; set; }
        public string SECOND_PATH { get; set; }
    }
    
}
