//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WuKeSong.Models
{
    public partial class LAB_TEST_MASTER
    {
        public decimal SERIAL_NO { get; set; }
        public string TEST_ID { get; set; }
        public string PATIENT_ID { get; set; }
        public string VISIT_ID { get; set; }
        public string TEST_REQ_ID { get; set; }
        public string HIS_TEST_ID { get; set; }
        public string TEST__NO { get; set; }
        public string TEST_NAME { get; set; }
        public string TEST_CODE { get; set; }
    }
    
}
