//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WuKeSong.Models
{
    public partial class PATIENT_VISIT
    {
        public decimal SERIAL_NO { get; set; }
        public decimal MPIML_SERIAL_NO { get; set; }
        public string VISIT_TYPE { get; set; }
        public string HIS_VISIT_ID { get; set; }
        public string HIS_VISIT_SUB_ID { get; set; }
        public string DEPARTMENT_CODE { get; set; }
        public string DEPARTMENT_NAME { get; set; }
        public string WARD_CODE { get; set; }
        public string WARD_NAME { get; set; }
        public Nullable<System.DateTime> VISIT_TIME { get; set; }
        public string VISIT_ID { get; set; }
    }
    
}
