//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace WuKeSong.Models
{
    public partial class UNITS_IN_CONTRACT_DICT
    {
        public string DICT_ID { get; set; }
        public decimal DICT_VER { get; set; }
        public decimal DICT_VER_PREVIOUS { get; set; }
        public string CODE_TYPE { get; set; }
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string INPUT_CODE { get; set; }
        public string ALIAS { get; set; }
        public string LOCATION_ID { get; set; }
        public Nullable<decimal> LOCATION_VER { get; set; }
        public string MAILING_ADDR { get; set; }
        public string ZIP_CODE { get; set; }
        public string SUBORDINATE_TO_ID { get; set; }
        public Nullable<decimal> SUBORDINATE_TO_VER { get; set; }
    }
    
}
