USE [FengQiLu]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CVD]') AND type in (N'U'))
DROP TABLE [dbo].[CVD]
GO

CREATE TABLE [dbo].[CVD] (
[ID] int IDENTITY(1,1) NOT NULL,
[Instance_ID] int,
[Patient_ID] nvarchar(max),
[Patient_Name] nvarchar(255),
[Patient_Gender] nvarchar(255),
[Patient_Birthday] datetime,
[ExactAge] int,
[Patient_Tel] int,
[Admission] datetime,
[Discharge] datetime,
[Diagnosis] nvarchar(max),
[Complications_Diabetes] bit NOT NULL,
[Complications_Hypertension] bit NOT NULL,
[Complications_Hyperlipidemia] bit NOT NULL,
[Complications_CI] bit NOT NULL,
[Complications_CRI] bit NOT NULL,
[Complications_PAD] bit NOT NULL,
[StrokeExperience] bit NOT NULL,
[OMI] bit NOT NULL,
[FamilyHistoryFlag] bit NOT NULL,
[Scenario_Smooking] bit,
[Scenario_Anthropometrics_BodyHeight] float,
[Scenario_Anthropometrics_BodyWeight] float,
[Scenario_Anthropometrics_BMI] float,
[Scenario_PhysiologicalParameters_HR] float,
[Scenario_PhysiologicalParameters_BpSys] float,
[Scenario_PhysiologicalParameters_BpDia] float,
[Medication_Aspirin] bit,
[Medication_Clopidogrel] bit,
[Medication_TirofibanHydrochloride] bit,
[Medication_Statins] bit,
[Medication_Prolol] bit,
[Medication_ACEIARB] bit,
[PCI_SurgeryDay] datetime,
[PCI_Emergency_PCI] bit,
[PCI_CA_LAD_StenosisLevel] int,
[PCI_CA_LAD_StenosisSegmentsRaw] int,
[PCI_CA_DIAG_StenosisLevel] int,
[PCI_CA_LCX_StenosisLevel] int,
[PCI_CA_LCX_StenosisSegmentsRaw] int,
[PCI_CA_OM_StenosisLevel] int,
[PCI_CA_RCA_StenosisLevel] int,
[PCI_CA_RCA_StenosisSegmentsRaw] int,
[PCI_CA_LM_StenosisLevel] int,
[PCI_CA_RenalArtery_StenosisLevel] int,
[PCI_CA_LAD_PCI] int,
[PCI_CA_DIAG_PCI] int,
[PCI_CA_LCX_PCI] int,
[PCI_CA_RAC_PCI] int,
[PCI_CA_LM_PCI] int,
[Scenario_Test_TC] float,
[Scenario_Test_TG] float,
[Scenario_Test_LDL] float,
[Scenario_Test_HDL] float,
[Scenario_Test_APOA1] float,
[Scenario_Test_APOB] float,
[Scenario_Test_a] float,
[Scenario_Test_CRE] float,
[Scenario_Test_BUN] float,
[Scenario_Test_FBG] float,
[Scenario_Test_CK] float,
[Scenario_Test_CK-MB] float,
[Scenario_Test_TNT] float,
[Scenario_Test_HCY] float,
[Scenario_Test_CYC] float,
[Scenario_Test_UA] float,
[Scenario_Test_BNP] float,
[Scenario_Test_HGB] float,
[Scenario_Test_WBC] float,
[Scenario_Test_Neutrophil] float,
[Scenario_Test_D-Dimer] float,
[Scenario_Test_CRP] float,
[Scenario_Test_IL-6] float,
[Scenario_Test_CRE_48h] float,
[Scenario_Test_BUN_48h] float,
[Scenario_Echo_EF] float,
[Scenario_Echo_LVDs] float,
[Scenario_Echo_LVDd] float,
[Scenario_Echo_IVS] float,
[Scenario_Echo_LVPW] float,
[Scenario_Echo_LAD] float,
[Scenario_CarotidUS] nvarchar(max),
[Scenario_RenalArteryUS] int,
[FollowUp_Death] nvarchar(max),
[FollowUp_MI] nvarchar(max),
[FollowUp_Revascularization] nvarchar(max),
[FollowUp_HF] nvarchar(max),
[FollowUp_Readmission] nvarchar(max),
[FollowUp_FollowUpLabSheet] nvarchar(max),
[FollowUp_CardiacEvent] nvarchar(max),
CONSTRAINT [PK_CVD] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO