//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace YuQuan.Models
{
    public partial class ChangeRecord
    {
        public ChangeRecord()
        {
            this.Fact = new HashSet<Fact>();
        }
    
        public int Id { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public string OldState { get; set; }
        public string NewState { get; set; }
        public string Reason { get; set; }
    
        public virtual ICollection<Fact> Fact { get; set; }
        public virtual ClinicalProblemInstance ClinicalProblemInstance { get; set; }
    }
    
}
