//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace YuQuan.Models
{
    public partial class Fact
    {
        public int Id { get; set; }
        public Nullable<double> NumericValue { get; set; }
        public Nullable<bool> BooleanValue { get; set; }
        public string StringValue { get; set; }
        public Nullable<bool> IsAbnormal { get; set; }
        public Nullable<decimal> Confidence { get; set; }
        public string LifeSpan { get; set; }
    
        public virtual Encounter Encounter { get; set; }
        public virtual ChangeRecord ChangeRecord { get; set; }
        public virtual Report Report { get; set; }
        public virtual ContextItemDefinition ContextItemDefinition { get; set; }
    }
    
}
