//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace YuQuan.Models
{
    public partial class KBEntities : DbContext
    {
        public KBEntities()
            : base("name=KBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChangeRecord> ChangeRecord { get; set; }
        public DbSet<ClinicalProblemDefinition> ClinicalProblemDefinition { get; set; }
        public DbSet<ClinicalProblemInstance> ClinicalProblemInstance { get; set; }
        public DbSet<ContextItemDefinition> ContextItemDefinition { get; set; }
        public DbSet<EBM> EBM { get; set; }
        public DbSet<Encounter> Encounter { get; set; }
        public DbSet<Event> Event { get; set; }
        public DbSet<Fact> Fact { get; set; }
        public DbSet<MedicalOrderDefinition> MedicalOrderDefinition { get; set; }
        public DbSet<MedicalOrderDefinition_EBM_Association> MedicalOrderDefinition_EBM_Association { get; set; }
        public DbSet<MedicalOrderInstance> MedicalOrderInstance { get; set; }
        public DbSet<PhaseDefinition> PhaseDefinition { get; set; }
        public DbSet<PhaseDefinition_EBM_Association> PhaseDefinition_EBM_Association { get; set; }
        public DbSet<PlanDefinition> PlanDefinition { get; set; }
        public DbSet<PlanDefinition_EBM_Association> PlanDefinition_EBM_Association { get; set; }
        public DbSet<PlanInstance> PlanInstance { get; set; }
        public DbSet<Report> Report { get; set; }
        public DbSet<TaskDefinition> TaskDefinition { get; set; }
        public DbSet<TaskDefinition_EBM_Association> TaskDefinition_EBM_Association { get; set; }
        public DbSet<TriggerRule> TriggerRule { get; set; }
        public DbSet<TriggerRule_EBM_Association> TriggerRule_EBM_Association { get; set; }
        public DbSet<ClinicalProblemDefinition_ContextItemDefinition_Association> ClinicalProblemDefinition_ContextItemDefinition_AssociationSet { get; set; }
        public DbSet<ClinicalProblemDefinition_PlanDefinition_Association> ClinicalProblemDefinition_PlanDefinition_AssociationSet { get; set; }
    }
}
