//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace YuQuan.Models
{
    public partial class MedicalOrderDefinition
    {
        public string OrderType { get; set; }
        public string AdministrationRoute { get; set; }
        public string TemporalType { get; set; }
        public string Frequency { get; set; }
        public string Dosage { get; set; }
        public string AdditionalInstruction { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string CodingSystem { get; set; }
        public string Description { get; set; }
    
        public virtual TaskDefinition TaskDefinition { get; set; }
    }
    
}
