//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace YuQuan.Models
{
    public partial class PhaseDefinition
    {
        public PhaseDefinition()
        {
            this.TaskDefinition = new HashSet<TaskDefinition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Duration { get; set; }
        public string Period { get; set; }
    
        public virtual PlanDefinition PlanDefinition { get; set; }
        public virtual ICollection<TaskDefinition> TaskDefinition { get; set; }
    }
    
}
