//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace YuQuan.Models
{
    public partial class PlanDefinition
    {
        public PlanDefinition()
        {
            this.PhaseDefinition = new HashSet<PhaseDefinition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Duration { get; set; }
        public string Objective { get; set; }
        public string Cost { get; set; }
        public string Criteria { get; set; }
        public string Version { get; set; }
        public string Status { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    
        public virtual ICollection<PhaseDefinition> PhaseDefinition { get; set; }
    }
    
}
