//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace YuQuan.Models
{
    public partial class PlanInstance
    {
        public string State { get; set; }
        public string CurrentPhase { get; set; }
        public int Id { get; set; }
    
        public virtual PlanDefinition PlanDefinition { get; set; }
        public virtual ClinicalProblemInstance ClinicalProblemInstance { get; set; }
    }
    
}
