//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace YuQuan.Models
{
    public partial class TaskDefinition
    {
        public TaskDefinition()
        {
            this.MedicalOrderDefinition = new HashSet<MedicalOrderDefinition>();
        }
    
        public bool Optional { get; set; }
        public bool MultiSelect { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string CodingSystem { get; set; }
    
        public virtual PhaseDefinition PhaseDefinition { get; set; }
        public virtual ICollection<MedicalOrderDefinition> MedicalOrderDefinition { get; set; }
    }
    
}
