//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace YuQuan.Models
{
    public partial class ClinicalProblemDefinition_ContextItemDefinition_Association
    {
        public int ContextItemDefinition_Id { get; set; }
        public int ClinicalProblemDefinition_Id { get; set; }
    }
    
}
