//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace YuQuan.Models
{
    public partial class ContextItemDefinition
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public string Unit { get; set; }
        public string DataType { get; set; }
        public string Code { get; set; }
        public string CodingSystem { get; set; }
        public string ReferenceRange { get; set; }
        public Nullable<decimal> UpperBound { get; set; }
        public Nullable<decimal> LowerBound { get; set; }
        public string DefaultValue { get; set; }
        public string InputCode { get; set; }
        public string Version { get; set; }
        public string Status { get; set; }
        public string NavigationPath { get; set; }
        public string Type { get; set; }
        public string Author { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
    }
    
}
