//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace YuQuan.Models
{
    public partial class Encounter
    {
        public Encounter()
        {
            this.Fact = new HashSet<Fact>();
            this.ClinicalProblemInstance = new HashSet<ClinicalProblemInstance>();
            this.Event = new HashSet<Event>();
        }
    
        public int Id { get; set; }
        public string FK_EMR_Encounter_Id { get; set; }
    
        public virtual ICollection<Fact> Fact { get; set; }
        public virtual ICollection<ClinicalProblemInstance> ClinicalProblemInstance { get; set; }
        public virtual ICollection<Event> Event { get; set; }
    }
    
}
