//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace YuQuan.Models
{
    public partial class Event
    {
        public Event()
        {
            this.Report = new HashSet<Report>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string EventType { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual Encounter Encounter { get; set; }
        public virtual ICollection<Report> Report { get; set; }
    }
    
}
