//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace SanQingShan.Models
{
    public partial class CPEntities : DbContext
    {
        public CPEntities()
            : base("name=CPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CP_EXAM> CP_EXAM { get; set; }
        public DbSet<CP_ORDER> CP_ORDER { get; set; }
        public DbSet<CP_VITAL_SIGN> CP_VITAL_SIGN { get; set; }
        public DbSet<CP_MEDICAL_DOC> CP_MEDICAL_DOC { get; set; }
        public DbSet<CP_LAB_TEST> CP_LAB_TEST { get; set; }
        public DbSet<CP_VISIT> CP_VISIT { get; set; }
    }
}
