//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SanQingShan.Models
{
    public partial class CP_LAB_TEST
    {
        public int Id { get; set; }
        public string HOSPITAL_ID { get; set; }
        public string OUTPATIENT_ID { get; set; }
        public string CP_ID { get; set; }
        public string REPORT_ITEM_NAME { get; set; }
        public string RESULT_VALUE { get; set; }
        public string RESULT_UNIT { get; set; }
        public string ABNORMAL_INDICATOR { get; set; }
        public Nullable<System.DateTime> REPORT_TIME { get; set; }
        public string TEST_NO { get; set; }
        public string ITEM_NO { get; set; }
        public string VID { get; set; }
        public string ORDER_ID { get; set; }
    }
    
}
