//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SanQingShan.Models
{
    public partial class CP_MEDICAL_DOC
    {
        public int Id { get; set; }
        public string CP_ID { get; set; }
        public string FULL_PATH { get; set; }
        public string FILE_EXTENSION { get; set; }
    }
    
}
