//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SanQingShan.Models
{
    public partial class CP_ORDER
    {
        public int Id { get; set; }
        public string HOSPITAL_ID { get; set; }
        public string CP_ID { get; set; }
        public string OUTPATIENT_ID { get; set; }
        public string ORDER_TYPE_ID { get; set; }
        public string ORDER_CONTENT { get; set; }
        public string DOSAGE { get; set; }
        public string UNIT { get; set; }
        public string METHOD { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public string FREQ { get; set; }
        public string FREQ_UNIT { get; set; }
        public string EXPECTED_EXECUTIVE_TIME { get; set; }
        public string ISSUER { get; set; }
        public string TERMINATOR { get; set; }
        public string EXECUTOR { get; set; }
        public string CHECKER { get; set; }
        public Nullable<System.DateTime> REAL_EXECUTIVE_TIME { get; set; }
    }
    
}
