//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SanQingShan.Models
{
    public partial class Feedback
    {
        public Feedback()
        {
            this.Answer = new HashSet<Answer>();
        }
    
        public int Id { get; set; }
    
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual ICollection<Answer> Answer { get; set; }
        public virtual Subject Subject { get; set; }
    }
    
}
