//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace SanQingShan.Models
{
    public partial class QuestionnaireContainer : DbContext
    {
        public QuestionnaireContainer()
            : base("name=QuestionnaireContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Concept> ConceptSet { get; set; }
        public DbSet<Answer> AnswerSet { get; set; }
        public DbSet<Choice> ChoiceSet { get; set; }
        public DbSet<Questionnaire> QuestionnaireSet { get; set; }
        public DbSet<Feedback> FeedbackSet { get; set; }
        public DbSet<Subject> SubjectSet { get; set; }
    }
}
